### PR TITLE
Refactor addClass and removeClass

### PR DESCRIPTION
**Pull request by nathanhammond**
The existing behavior:
- Relied on newer DOM and JS APIs.
- Branched for FastBoot, resulting in different behavior in different environments. This is a debugging nightmare.
- Did not remove multiple instances of a class name from an element.
- Did not ensure that the class name it was removing matched at token boundaries.
- Did not have tests.

This also moves the utility's location to the default Ember location. I've included a stub for external API compatibility which can electively be removed.

### CODE REVIEW

**Comment by billdami** [comment]
@nathanhammond did you happen to test your PR with a `environment=production` build? I am seeing an issue on the latest release, 1.0.1, where classes are not being applied to the body in FastBoot, but only on production builds (this on ember 3.1.2). I tried your PR's branch, but it seemed to exhibit the same issue in my app.

**Comment by nathanhammond** [comment]
@billdami Can you create a simplified reproduction as a repo I can just `npm i && ember serve`? If so I'll get a test in place and address the issue.

**Comment by billdami** [comment]
@nathanhammond sure, I'll give that a try

**Comment by billdami** [comment]
@nathanhammond so it appears it might be an app/environment related issue..as I'm not able to reproduce it in the test repo I just created. But just for reference, here's the repo:

https://github.com/billdami/ember-body-class-prod-test

**Comment by nathanhammond** [comment]
@billdami I've gone ahead and forked this project. Try `ember-body-class2`.

**Pull request closed without merging**
