### PR TITLE
Enable dynamically updating of the body classNames

### PR DESCRIPTION
**Pull request by ashrafhasson**
Hello there,

I've created this fork, and subsequently this PR, out of necessity but credit goes to @bardzusny for suggesting it really. Would appreciate your feedback on this PR.

Thanks for this addon, it really is useful.

### CODE REVIEW

**Comment by mansona** [comment]
Hey @ashrafhasson, thanks for the PR 👍 

I'm wondering what the use case for this change is? Also, have you tried the addon recently? there have been quite a few changes that have fixed a lot of other people's issues and I wonder if your use case is now fixed 🤔

**Comment by ashrafhasson** [comment]
Hi @mansona, I have an app that needs to change the body class based on whether the login page is displayed or the rest of the app. When the login page is displayed, the class name is set to "login" which changes the appearance of the page and all other classes are not present at that point. Additionally, I have a `sidebarClosed` property in the `application` route that also adds/removes a class to the `body` element based on whether it is active or not.

**Comment by mansona** [comment]
@ashrafhasson could you rebase please? I'm happy to merge this once the tests pass after this has been rebased 😄

**Comment by ashrafhasson** [comment]
@mansona rebase against master I presume. I'll do that soon. thanks! :)

**Comment by mansona** [comment]
@ashrafhasson thanks for this 👍 I'm wondering if you could add a test that covers this behaviour? 🤔 it would be quite nice to have to make sure that we don't regress at any point in the future

**Comment by ashrafhasson** [comment]
@mansona yeah I was working on a test and other priorities took over but I will try to include one soon :)

**Comment by mansona** [comment]
@ashrafhasson thanks for adding the test 🎉 it seems to be covering what I would expect and is nice and simple 😍 

Although Travis is having some issues 🤔 It seems to be the slightly older versions of Ember that are failing, maybe you could take a look and see if you can recreate locally with ember-try?

**Comment by ashrafhasson** [comment]
@mansona yeah it was passing locally, I'll try with ember-try and see what appears to be the issue. Thanks! :)

**Comment by ashrafhasson** [comment]
I've missed waiting for `visit` in the test which ember 2.16/2.18 did not like.

**Comment by mansona** [comment]
Released in v1.1.0 🎉

**Pull request merged**
